CONFIG_CPP=y
CONFIG_STD_CPP23=y
CONFIG_CPP_EXCEPTIONS=y
CONFIG_REQUIRES_FULL_LIBCPP=y

CONFIG_MAIN_STACK_SIZE=8192

# --- Multi-core Support ---
CONFIG_SMP=n
CONFIG_MP_MAX_NUM_CPUS=2
CONFIG_DCACHE=n

# --- Display Framework ---
CONFIG_DISPLAY=y
CONFIG_ILI9341=y

# --- Modern Zephyr LVGL Core Initialization ---
CONFIG_LVGL=y
CONFIG_LV_USE_ILI9341=y
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_Z_VDB_SIZE=20
CONFIG_LV_Z_MEM_POOL_SIZE=32768
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_Z_DOUBLE_VDB=y
CONFIG_LV_USE_LOG=y
# CONFIG_LV_COLOR_16_SWAP=y

# --- Hardware System Specs ---
CONFIG_LOG=y
CONFIG_DMA=y
CONFIG_SPI=y
