manifest:
  self:
    path: .

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nbergmann28
      url-base: https://github.com/nbergmann28

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis_6
          - hal_espressif
          - lvgl
  
    - name: opentempo
      repo-path: opentempo
      revision: main
      remote: nbergmann28
